colourededgerxlsx: colourededgerxlsx.00

colourededgerxlsx.00:
	@../R/colourededgerxlsx.r --verbose --seedtables=$@.BAL334.SEED.tsv,$@.BAL450.SEED.tsv --outxlsx=$@.xlsx $@.tsv.gz
	@echo "This is *not* an automated test, check $@.xlsx manually!"
